CREATE TABLE [dbo].[T_POS_ONL] (
    [POS_ONL_ID]       BIGINT       IDENTITY (1, 1) NOT NULL,
    [INVOICE_NO]       VARCHAR (20) NULL,
    [INVOICE_DATE]     DATETIME     NULL,
    [ORDER_NO]         VARCHAR (50) NULL,
    [PRODUCT_NAME]     VARCHAR (50) NULL,
    [PRODUCT_CODE]     VARCHAR (50) NULL,
    [QTY]              INT          NULL,
    [UNIT_PRICE]       VARCHAR (50) NULL,
    [TRANSACTION_TYPE] INT          NULL,
    [CREDIT_NOTE_NO]   VARCHAR (50) NULL,
    [DRIVER_CODE]      VARCHAR (20) NULL,
    [VEHICLE_NUMBER]   VARCHAR (20) NULL,
    [IS_PROCESSED]     BIT          NULL,
    [CREATED_DATE]     DATETIME     NULL,
    [CREATED_BY]       INT          NULL,
    CONSTRAINT [PK_T_POS_ONL] PRIMARY KEY CLUSTERED ([POS_ONL_ID] ASC)
);

